### ISSUE TITLE
Communicating with Bentham TMc300 monochromator

### ISSUE THREAD

**Issue by kemhmup** [BenthamInstruments/bendev#4]
As a project in my master I have to communicate in python with the TMc300 monochromator. We tried to use SCPI commands you listed in the read.me. *IDN? did work but both of these below did not.
```
my_tls.write("SYSTEM:REMOTE")
my_tls.query("MONO:GOTO? 555")
```
After writing them and waiting for the monochromator to execute the next command _print("test")_ it never does so. We cannot hear any sound suggesting that the motor did move. No error is generated either.
Are those commands understood by the monochromator we use? If not, what do you suggest we do to communicate in python with the device?
Thank you very much

**Comment by MarkusFF** [comment]
If you have a TMC300 monochromator, most likely it does not have the SCPI protocol built in, these are typically controlled via the BenHW windows SDK. Could you please contact our technical support team with the details of the monochromator (model, serial number) and we can look into options for this.

https://support.bentham.co.uk/support/tickets/new
